### ISSUE TITLE
`longer` hue interpolation is backwards

### ISSUE THREAD

**Issue by argyleink** [LeaVerou/color.js#277]
Screenshot from this Codepen https://codepen.io/argyleink/pen/poZVPyJ

<img width="1153" alt="Screenshot 2023-01-25 at 3 09 34 PM" src="https://user-images.githubusercontent.com/1134620/214712547-c12fdbbb-c06b-4e27-9707-92d0bd5f2d17.png">

Chrome and Safari both produce the same `longer` hue interpolation method, ColorJS produces the same hues but in the opposite direction. Is it a ColorJS bug or a bug in both Safari and Chromium?

**Comment by facelessuser** [comment]
I'm thinking something must have been interpreted wrong in the spec, or they all copied off each other 🙃 . In all seriousness, I only say this because the browsers not only produce it backward, but the hue passes through purple twice. They are interpreting shorter, but then keep going until they reach purple again. The intent of the spec is to take the long way around towards green and then end up on purple.

Now, the spec has been updated a couple of times, so maybe the spec no longer matches the intent? I know this area had been corrected a few times. I had implemented this directly from the spec some time ago, and I believe when I did it, it matched the color.js approach. I'm still running with that approach, and it does not pass through purple twice and follows the long way around, just like color.js.

Example here:

https://facelessuser.github.io/coloraide/playground/?code=import%20coloraide%0Acoloraide%2e__version__%0AColor%2einterpolate%28%5B%27hsl%28180deg%20100%25%2075%25%29%27%2C%20%27hsl%28240deg%20100%25%2075%25%29%27%5D%2C%20space%3D%27hsl%27%2C%20hue%3D%27shorter%27%29%0AColor%2einterpolate%28%5B%27hsl%28180deg%20100%25%2075%25%29%27%2C%20%27hsl%28240deg%20100%25%2075%25%29%27%5D%2C%20space%3D%27hsl%27%2C%20hue%3D%27longer%27%29%0AColor%2einterpolate%28%5B%27hsl%28180deg%20100%25%2075%25%29%27%2C%20%27hsl%28240deg%20100%25%2075%25%29%27%5D%2C%20space%3D%27hsl%27%2C%20hue%3D%27increasing%27%29%0AColor%2einterpolate%28%5B%27hsl%28180deg%20100%25%2075%25%29%27%2C%20%27hsl%28240deg%20100%25%2075%25%29%27%5D%2C%20space%3D%27hsl%27%2C%20hue%3D%27decreasing%27%29

**Comment by facelessuser** [comment]
Here's what the spec says:

```js
if (0 < θ₂ - θ₁ < 180) {
  θ₁ += 360;
}
else if (-180 < θ₂ - θ₁ <= 0) {
  θ₂ += 360;
}
```

Here's what color.js is doing.

```js
if (-180 < angleDiff && angleDiff < 180) {
	if (angleDiff > 0) {
		a2 += 360;
	}
	else {
		a1 += 360;
	}
}
```

Ignoring the different approaches of the conditionals, it looks like the spec mistakingly mixed up θ₁ and θ₂  when incrementing by 360. And anyone who implemented after such a change is probably doing it incorrectly.

**Comment by facelessuser** [comment]
Never mind. I did not look at the example close enough. Things like Safari preview are doing it correctly, from what I understand. It is colorjs.io that is doing it incorrectly. The CSS color spec seems to match the intention. I hadn't realized colorjs.io was doing it the reverse way (reversing the angles). I just double-checked my own implementation (code), and I match the spec as well and it is different from what colorjs.io is doing.

They must have "fixed" something at some time and broke it.

**Comment by facelessuser** [comment]
Seems to be related to this issue: https://github.com/LeaVerou/color.js/issues/156. I think they just didn't realize they had their hue increments backward.
