### ISSUE TITLE
massive spike in dependencies, including security vulnerabilities

### ISSUE THREAD

**Issue by electrovir** [LeaVerou/color.js#315]
Some went seriously wrong with the [version 0.4.4 release](https://www.npmjs.com/package/colorjs.io/v/0.4.4?activeTab=dependencies): it has 401 direct dependencies, including security vulnerabilities, while [version 0.4.3](https://www.npmjs.com/package/colorjs.io/v/0.4.3?activeTab=dependencies) has 0 dependencies.

**Comment by LeaVerou** [comment]
Yikes, thanks for letting us know! My first thought was that something that was a dev dependency must have been added as a regular dependency, but it doesn't look like it. Investigating…

**Comment by LeaVerou** [comment]
Fixed in [v0.4.4-patch.1](https://www.npmjs.com/package/colorjs.io)! Thanks again so much for bringing this to our attention! Still no clue how this happened. 🤷🏽‍♀️

**Comment by jgerigmeyer** [comment]
@LeaVerou Unfortunately while `v0.4.4-patch.1` is installed correctly as the `latest` release, it doesn't satisfy common semver ranges -- for example, existing projects with `"colorjs.io": "^0.4.3"` will now get `v0.4.4` installed instead of the patched release. Would you consider re-releasing as `v0.4.5`?
