### ISSUE TITLE
Oklab matrix is not 64bit accurate

### ISSUE THREAD

**Issue by svgeesus** [LeaVerou/color.js#356]
Issue forked from [this discussion](https://github.com/LeaVerou/color.js/pull/352/files#r1398416103), @facelessuser wrote:

> the current Oklab matrix is not exact enough to give a decent white and will introduce a notable error

> recalculating Oklab with 64 bit precision eliminate the inaccuracies near achromatic values

**Comment by facelessuser** [comment]
Since it appears you are open to a 64 bit matrix, I can issue a pull request. I'll provide the work I used to calculate them as well. The work may not be in JS as the libraries I've been playing with over the last number of days have frustrated me, but in time, I imagine someone can get it all in a JS solution.

**Comment by svgeesus** [comment]
> Since it appears you are open to a 64 bit matrix, I can issue a pull request. I'll provide the work I used to calculate them as well. The work may not be in JS as the libraries I've been playing with over the last number of days have frustrated me, but in time, I imagine someone can get it all in a JS solution.

The main thing is to know where the values came from. Whether that derivation was in JS, Python, MatLab, Rust does not particularly matter. Thanks for the clear documentation.
