### ISSUE TITLE
Converting sRGB to LCH when: Red Green and Blue are Equal (Bug)

### ISSUE THREAD

**Issue by Vac1911** [LeaVerou/color.js#87]
When attempting to convert an sRGB  to LCH, where the chroma should be 0, produces unexpected values in the Chroma and Hue channels. The chroma value appears to have a floating point error when it should be 0, and the hue value is always NaN, which causes math problems.

Take the following examples:
```
new Color('srgb', [0.1, 0.1, 0.1]).to('lch').coords
(3) [9.010443527068848, 0.000006337680094534959, NaN]

new Color('srgb', [0.13333, 0.13333, 0.13333]).to('lch').coords
(3) [13.227498037447411, 0.000007406287423610401, NaN]

new Color('srgb', [0.4, 0.4, 0.4]).to('lch').coords
(3) [43.192291386569806, 0.000014999406423138985, NaN]
```

**Comment by LeaVerou** [comment]
`NaN` is intentional, to indicate the hue is undefined. This is pretty consistent with most other color libraries.
The chroma, we should look into.

**Comment by facelessuser** [comment]
So, I was looking into this as well as it bothered me greatly, not that chroma didn't zero out because I don't think the algorithm will ever exactly zero out all sRGB grayscale colors, but that chroma was still so big in some cases:

```js
> new Color('rgb(51 51 51)').to('lch')
Color$1 {
  _spaceId: 'lch',
  toString: [Function: toString],
  coords: [ 21.246677841882843, 0.004699669710246514, NaN ],
  alpha: 1
}
```

I ran all achromatic sRGB values through LCH and noted that `chroma` gets quite high along with `a` and `b` in L\*a\*b\*.

```
srgb: maximum chroma: 0.014636
srgb: maximum a: 0.003817
srgb: maximum b: 0.014130
```

And yet, on http://www.brucelindbloom.com/index.html?Math.html they get much cleaner values. And I know they were referenced for a lot of the algorithms.

<img width="457" alt="Screen Shot 2021-04-07 at 9 14 25 AM" src="https://user-images.githubusercontent.com/1055125/113890775-b1883080-9781-11eb-9557-c0a98b256241.png">

So I've gone over conversions a number of times and generally see no issues. So I figured it had to be a difference in the XYZ matrices.

So, I inspected the page to snoop out the variables for their XYZ matrices. I was able to see the variable they stored the matrices in as the code is not compressed and I dumpped them. You can see the difference below:

```js
	// This matrix was calculated directly from the RGB and white chromaticities
	// when rounded to 8 decimal places, it agrees completely with the official matrix
	// see https://github.com/w3c/csswg-drafts/issues/5922
	// toXYZ_M: [
	// 	[ 0.41239079926595934, 0.357584339383878,   0.1804807884018343  ],
	// 	[ 0.21263900587151027, 0.715168678767756,   0.07219231536073371 ],
	// 	[ 0.01933081871559182, 0.11919477979462598, 0.9505321522496607  ]
	// ],

	toXYZ_M: [
		[0.4124564390896922, 0.357576077643909, 0.18043748326639894],
		[0.21267285140562253, 0.715152155287818, 0.07217499330655958],
		[0.0193338955823293, 0.11919202588130297, 0.9503040785363679]
	],

	// This matrix is the inverse of the above;
	// again it agrees with the official definiton when rounded to 8 decimal places
	// fromXYZ_M: [
	// 	[  3.2409699419045226,  -1.537383177570094,   -0.4986107602930034  ],
	// 	[ -0.9692436362808796,   1.8759675015077202,   0.04155505740717559 ],
	// 	[  0.05563007969699366, -0.20397695888897652,  1.0569715142428786  ]
	// ],

	fromXYZ_M: [
		[3.2404541621141045, -1.5371385127977166, -0.498531409556016],
		[-0.9692660305051868, 1.8760108454466942, 0.041556017530349834],
		[0.055643430959114726, -0.2040259135167538, 1.0572251882231791]
	],
```

Now, looking at the previous example, and rerunning things with the new matricies. I get much cleaner results:

```js
> new Color('rgb(51 51 51)').to('lch')
Color$1 {
  _spaceId: 'lch',
  toString: [Function: toString],
  coords: [ 21.24673121272818, 0.0000038628909560274165, NaN ],
  alpha: 1
}
```

As a matter of fact, running all sRGB achromatic colors through my previous tests show dramatically lower `chroma`, `a`, and `b` for achromatic sRGB values overall. So much so, that I'd feel pretty okay rounding chroma to zero in these cases.

```
srgb: maximum chroma: 0.000012
srgb: maximum a: 0.000011
srgb: maximum b: 0.000005
```

For comparison to the old results:

```
srgb: maximum chroma: 0.014636
srgb: maximum a: 0.003817
srgb: maximum b: 0.014130
```

Now, am I suggesting the above matrix should be used? 🤷🏻

I'm not an expert in this area, so I'm not 100% sure of the impact. Running this through my project's local tests, I didn't see any significant issues in any critical tests. I also haven't yet walked through all the math in their calculator to understand how they came up with those values.

This is more an interesting observation at this point. But maybe something to look into 🤷🏻.

**Comment by facelessuser** [comment]
So I've gone through the math, I now understand why color.js is so off.

The sRGB matrix that color.js uses is based off a calculated white point for D65:

```py
white = [0.3127 / 0.3290, 0.3290 / 0.3290, 0.3583 / 0.3290]
```

This gives us

```py
[0.9504559270516716, 1.0, 1.0890577507598784]
```

But then we use the following D65 white point any time we do chromatic adaption:

```py
[0.95047, 1.00000, 1.08883]
```

This gives us quite a bit of error.

With the following code, doing nothing tricky, I follow the algorithm calculating the XYZ conversion matrix based on this algorithm: http://www.brucelindbloom.com/index.html?Math.html.

I will output the first results based on using a consistent white point with what is used in chromatic adaption and then I'll output the same matrix with a calculated white point.

```py
import numpy as np

white_consistent = [0.95047, 1.00000, 1.08883]
white_calc = [0.3127 / 0.3290, 0.3290 / 0.3290, 0.3583 / 0.3290]

def get_matrix(wp):
    # Red to xyY
    xr = 0.64
    yr = 0.33
    # Green to xyY
    xg = 0.30
    yg = 0.60
    # Blue to xyY
    xb = 0.15
    yb = 0.06

    m = [
        [xr/yr, 1.0, (1.0-xr-yr)/yr],
        [xg/yg, 1.0, (1.0-xg-yg)/yg],
        [xb/yb, 1.0, (1.0-xb-yb)/yb]
    ]
    mi = np.linalg.inv(m)

    r, g, b = np.dot(wp, mi)
    rgb = [
        [r],
        [g],
        [b]
    ]
    rgb2xyz = np.multiply(rgb, m).transpose()
    xyz2rgb = np.linalg.inv(rgb2xyz)
    print(rgb2xyz)
    print(xyz2rgb)

print('======== Using a consistent white point with our chromatic adaption')
get_matrix(white_consistent)

print('======== Using the calculated white point')
get_matrix(white_calc)
```

The first results match what is used in the brucelindbloom calculator and give much better results.
The matches the matrix that is currently used.

```
======== Using a consistent white point with our chromatic adaption
[[0.41245644 0.35757608 0.18043748]
 [0.21267285 0.71515216 0.07217499]
 [0.0193339  0.11919203 0.95030408]]
[[ 3.24045416 -1.53713851 -0.49853141]
 [-0.96926603  1.87601085  0.04155602]
 [ 0.05564343 -0.20402591  1.05722519]]
======== Using the calculated white point
[[0.4123908  0.35758434 0.18048079]
 [0.21263901 0.71516868 0.07219232]
 [0.01933082 0.11919478 0.95053215]]
[[ 3.24096994 -1.53738318 -0.49861076]
 [-0.96924364  1.8759675   0.04155506]
 [ 0.05563008 -0.20397696  1.05697151]]
```

Based on this, I am much more confident with my opinion on this. My recommendation would be to use the matrix that is consistent with the white point that is being used everywhere else or update the white point in chromatic adaption to match what is used in the matrix calculations.

**Comment by facelessuser** [comment]
Depending on which direction you guys go in, it may be worth double-checking the math on the RGB matrices as well as they may suffer from the same flaw.

**Comment by facelessuser** [comment]
If it is any help, I've created a script to re-calculate the RGB-ish matrices: https://gist.github.com/facelessuser/7d3707734fa9bcf208ab4dabea830cdb.

Again, the alternative is to just recalculate the chromatic adaption matrix with the same white points used to generate the space2rgb and xyz2rgb matrices.

I'm interested to see which route color.js takes.

**Comment by svgeesus** [comment]
> The sRGB matrix that color.js uses is based off a calculated white point for D65:

> white = [0.3127 / 0.3290, 0.3290 / 0.3290, 0.3583 / 0.3290]

Yes. This is a fairly recent change, after I got a hold of the CIE 15 specification (normally paywalled). In general, if a number is actually defined as a rational number, I prefer to code it as a constant expression rather than calculate out the floating point value to some precision.

However, checking again that is still not right. 

1. the chromaticity coordinates are truncated  to four significant figures, while they are given to five in Table T.3 in section 11.3 "Tristimulus values, chromaticity coordinates of CIE Illuminants"
2. that table is calculated from the abridged 5nm

> But then we use the following D65 white point any time we do chromatic adaption:

> [0.95047, 1.00000, 1.08883]

Clearly this should only be defined once, and the definition should thus be the same everywhere it is used.

> Again, the alternative is to just recalculate the chromatic adaption matrix with the same white points used to generate the space2rgb and xyz2rgb matrices.

I think that is the better option. The CATs were calculated some time ago. But re-checking all the RGB ↔ XYZ matrices too, is certainly worth doing.

Meanwhile though I am thinking to revert the 

> white = [0.3127 / 0.3290, 0.3290 / 0.3290, 0.3583 / 0.3290]

to

> white = [0.95047, 1.00000, 1.08883]

until I track down the 1nm measurements *and* do the spectral calculation. That at least returns us to a self-consistent set of values.

BTW https://github.com/w3c/csswg-drafts/issues/5922 has some earlier sleuthing and explains why some of Lindbloom's calculations seem to be a bit off.

Thanks for tracing the causes of this.

**Comment by facelessuser** [comment]
> I think that is the better option. The CATs were calculated some time ago. But re-checking all the RGB ↔ XYZ matrices too, is certainly worth doing.

I was able to calculate them all, and they seem consistent with the following white points. It was all pretty straightforward (though I had to play around with ProPhoto to realize you rounded off the primaries to the same precision as the white point, but it made perfect sense after I realized it).

```py
x = 0.3127
y = 0.3290
z = 0.3583
white_calc_d65 = [x / y, y / y, z / y]

x = 0.3457
y = 0.3585
z = 0.2958
white_calc_d50 = [x / y, y / y, z / y]
```

I'm sure you know better than me in this area about what precision to use and such, but ultimately, just using a consistent white point seemed greatly reduce chroma for achromatic colors.  Granted, none of the color space specs I looked at were using the Lindbloom values for the white points, but it was helpful to confirm using a consistent white point helps. So, it makes sense to me that you'd prefer the CAT route. I kind of suspected that would be the case, but calculating that is beyond me at this time 🙃 .

**Comment by facelessuser** [comment]
So I couldn't put this down because I can be obsessive at times. I left the XYZ matrices alone. Found a spreadsheet online that can calculate the Bradford chromatic adaptions. I entered in the two white points that were used to calculate the XYZ matrices. I entered them in for D65 and D50 and got two matrices out:

```py
x = 0.3127
y = 0.3290
z = 0.3583
white_calc_d65 = [x / y, y / y, z / y]

x = 0.3457
y = 0.3585
z = 0.2958
white_calc_d50 = [x / y, y / y, z / y]

WHITES = {
    "D50": white_calc_d50,
    "D65": white_calc_d65
}


def d50_to_d65(xyz):
    """Bradford chromatic adaptation from D50 to D65."""

    m = [[0.955473421, -0.023098455, 0.063259243],
         [-0.028369710, 1.009995398, 0.021041441],
         [0.012314015, -0.020507649, 1.330365927]]

    return util.dot(m, xyz)


def d65_to_d50(xyz):
    """Bradford chromatic adaptation from D65 to D50."""

    m = [
        [1.047929793, 0.022946871, -0.050192266],
        [0.029627809, 0.990434427, -0.017073799],
        [-0.009243041, 0.015055191, 0.751874281]
    ]

    return util.dot(m, xyz)
```

Here's the cool part, zero chroma:

```py
>>> Color('grey').convert('lch').coords()
[53.58501346454909, 1.064841851930731e-07, nan]
>>> Color('white').convert('lch').coords()
[100.00000002063788, 1.7751193429472348e-07, nan]
>>> Color('black').convert('lch').coords()
[0.0, 0.0, nan]
```

I ran this for the full range of all the RGB-ish achromatic colors. And I got ~0 for `chroma`, `a`, and `b` all the way down.

```
srgb: maximum chroma: 0.000000
srgb: maximum a: 0.000000
srgb: maximum b: 0.000000
---
display-p3: maximum chroma: 0.000000
display-p3: maximum a: 0.000000
display-p3: maximum b: 0.000000
---
rec2020: maximum chroma: 0.000000
rec2020: maximum a: 0.000000
rec2020: maximum b: 0.000000
---
a98-rgb: maximum chroma: 0.000000
a98-rgb: maximum a: 0.000000
a98-rgb: maximum b: 0.000000
---
prophoto-rgb: maximum chroma: 0.000000
prophoto-rgb: maximum a: 0.000000
prophoto-rgb: maximum b: 0.000000
```

That's pretty spot on. Moral of the story is that we need all the matrices using the exact same white points.

**Comment by facelessuser** [comment]
I confirmed that the algorithm I'm using can generate the same incorrect matrix that is in use now. So I'm confident the calculations are correct.

```
===== To D65 =====
[[ 0.9554734214880751 -0.0230984549487647  0.0632592432005707]
 [-0.0283697093338638  1.0099953980813041  0.0210414411919173]
 [ 0.012314014864482  -0.020507649298899   1.3303659262421237]]
===== To D50 =====
[[ 1.0479297925449969  0.0229468706016097 -0.0501922662892052]
 [ 0.0296278087700559  0.9904344267538799 -0.0170737990634188]
 [-0.0092430406462045  0.0150551914902981  0.7518742814281371]]
```

For reference, the Bradford CAT matrix calculation I'm using is here: https://gist.github.com/facelessuser/e580d11043b003df889d5e7eece050c1.

In my own project, I just went ahead and regenerated all the matrices to make sure everything was proper. I didn't see any significant differences in any of the XYZ transforms, but obviously, the Bradford CAT was quite different than what is above.

Another bonus is that it fixed the Delta E comparison of black and white in the 76 and 2000 algorithm, so another win.

```py
>>> Color("white").delta_e('black', method="2000")
100.0
>>> Color("white").delta_e('black', method="76")
100.0
```

Anyways, I'm more than happy to issue any pull requests, but I assume you're going to want to dig in yourself 😄. Hopefully, all of this helped. Not sure I can offer much more information.

**Comment by svgeesus** [comment]
> I'm sure you know better than me in this area about what precision to use and such, 

_laughs in a deeply pained way_ 

CIE 15.3:2004 Table T.3 gives XYZ to 4 or 5 significant figures, and xy to 5 significant figures, and the two do not interconvert exactly. It also says that these are calculated from the 5nm interval data. It then says that the _normative_ definition is the spectral power distribution, not these figures. D65 and A are defined at 1nm intervals; C ,D50, D55 and D75 are only defined at 5nm intervals.

D65 X=95.04 Y=100.00 Z=108.88 x=0.31272 y=0.32903
D50 X=96.42 Y=100.00 Z=82.51 x=0.34567 y=0.35851

![image](https://user-images.githubusercontent.com/2506926/114104552-15e9e380-9899-11eb-96f6-900848715d15.png)

Oh and CIE 15.3:2004 is paywalled but the Draft International Standard can be [found online](https://haralick.org/DV/cie_2004_colorimetry.pdf); the 1nm data is "only on the CD-ROM" but also [is available online](https://www.rit.edu/cos/colorscience/rc_useful_data.php)

Meanwhile ASTM E‑308 Computing the Colors of Objects by Using the CIE System (also paywalled) [seems to be preferred](https://support.hunterlab.com/hc/en-us/articles/205721079-Illuminants-D65-versus-D65-ASTM-) and is [used by Lindloom](http://www.brucelindbloom.com/index.html?Eqn_ChromAdapt.html), and the XYZ values are given to 6 significant figures


D65 X=0.95047 Y=1.00000 Z=1.08883
D50 X=0.96422 Y=1.00000 Z=0.82521

The latter is what color.js uses (also the values for the other illuminants, in the CAT module).

I'm *this* close to writing or finding code to do the full conversion from 1nm spectral data just to find what the real value is to arbitrary precision.

> but ultimately, just using a consistent white point seemed greatly reduce chroma for achromatic colors.

Yes, absolutely. The same values and specified the same way (XYZ not xy).

The problem is that I re-used an old program I wrote like 5 years ago to calculate the RGB to/from XYZ matrices, and it used whitepoint x and y to 4 significant figures, and then immediately calculated XYZ from that. I [just pushed a change](https://github.com/w3c/csswg-drafts/commit/55e497b217f03bff5f534744719d6a7b019c18c3) to that utility to make it use the same ASTM XYZ values as color.js does.

**Comment by facelessuser** [comment]
>  I just pushed a change to that utility to make it use the same ASTM XYZ values as color.js does.

So are these the official white points you will support moving forward? Or just temporary?

**Comment by svgeesus** [comment]
Unless I do the first-principles spectral conversion and get different results in the first 5 figures, it will be these ones going forward.

I ran your Python program with these XYZ values, and got the same results as my JavaScript program.

**Comment by svgeesus** [comment]
So I tried recalculating everything (RGB to XYZ to RGB matrcies, Bradford CATs) with the ASTM values. But, despite being popular, the ASTM values are based on only 10nm spacing and they are significantly different from the CIE 15:2004 chromaticity values.

Next I did the same recalc everything, with the CIE 15:2004 six-digit chromaticity values. That worked, but the sRGB to XYZ and back matrices were too divergent from the ones in the official sRGB standard, for my liking.

So eventually I went for maximum compat, setting D50 and D65 based on the four-digit chromaticities that everyone seemed to use. 

```js
D50: [0.3457 / 0.3585, 1.00000, (1.0 - 0.3457 - 0.3585) / 0.3585],
D65: [0.3127 / 0.3290, 1.00000, (1.0 - 0.3127 - 0.3290) / 0.3290],
```

That gave me the same sRGB to XYZ and back values (when rounded to 8 decimals) as the sRGB standard. I recalculated the Bradford matrices for D50 to D65 and back. As a result, sRGB white now converts to `lch(100% 0.0000103 0)` which is a big improvement over `lch(99.999834% 0.0146365 0)`.

**Comment by facelessuser** [comment]
I actually recalculated all my matrices (Bradford CAT, sRGB <=> XYZ, etc.) and I now get a solid translation. It is dead on.

```py
>>> Color('white').convert('lab').coords()
[100.0, 0.0, 0.0]
```

I'm using:

```py
white_d65 = [0.95047, 1.00000, 1.08883]
white_d50 = [0.96422, 1.00000, 0.82521]
```

I don't know if it helps, but my matrix calculations are here: https://github.com/facelessuser/coloraide/tree/master/tools.

And I ended up with Bradford matrices of https://github.com/facelessuser/coloraide/blob/master/coloraide/spaces/_cat.py#L13

and sRGB <=> XYZ matrices of of https://github.com/facelessuser/coloraide/blob/master/coloraide/spaces/srgb.py#L17

**Comment by facelessuser** [comment]
Conversion has never been 100% perfect near zero, so there is still a little bit of flux:

```py
>>> Color('white').convert('lab').convert('srgb').coords()
[0.9999999999999992, 1.0000000000000002, 0.9999999999999997]
>>> Color('white').convert('lab').convert('srgb').convert('lab').coords()
[100.0, -5.551115123125783e-14, 2.220446049250313e-14]
```

But overall, it is generally way more consistent.

**Comment by facelessuser** [comment]
I just tried out the matrices in Color.js, and I was able to get the same results in Color.js. Cranking up the precision to 16, it is still just a zero chroma.

```js
> new Color('white').to('lch').toString({precision: 16})
'lch(100% 0 0)'
> new Color('white').to('lab').toString({precision: 16})
'lab(100% 0 0)'
```
